model_list:
  - model_name: github-gpt-4o # Model Alias to use for requests
    litellm_params:
      model: github/gpt-4o
      api_key: "os.environ/GITHUB_API_KEY"
  - model_name: github-gpt-4o-mini # Model Alias to use for requests
    litellm_params:
      model: github/gpt-4o-mini
      api_key: "os.environ/GITHUB_API_KEY"
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: "os.environ/GEMINI_API_KEY"
